apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: host-volume
      hostPath:
        path: /tmp
